### ISSUE TITLE
offsets for strange characters

### ISSUE THREAD

**Issue by Andrew-Kang-G** [VirusTotal/yara#1099]
I am currently using this wrapper, https://github.com/stellarbear/YaraSharp.

The following two return different offsets

Search word : Groupe

1) +W¥Groupe  => offset 4
2) Vv,Groupe => offset 3

They are supposed to be the same index, 3. no?
I want to get the same index like all the other regex libraries in javascript, c#, etc...

**Comment by plusvic** [comment]
Please check the file content in a hex editor. Some characters like ¥ may be encoded with two bytes instead of one, depending on the encoding used (UTF-8, etc). YARA doesn't have full support for unicode, YARA sees the file as sequence of bytes, not characters. That explains why in the first case the offset is 4, because from the 3 characters in front of "Groupe" one of them is actually two bytes. 

Re-open this issue if you confirm that the byte offset is incorrect.
