### ISSUE TITLE
Running entropy on groups or results

### ISSUE THREAD

**Issue by Plazmaz** [VirusTotal/yara#1127]
Hi, I'm attempting to create a rule that matches high entropy in a subset of a string. For instance, if my match was `example|(.*?)`, I would only want to return results where `$1` has a high entropy. Is it possible to this with yara? I'd also be fine with just checking the entropy of `example|.*?`, but I can't figure out how to run entropy only on matches. It seems like it's meant to work either with entire files or specific offsets. Is there a way to check this for all results found? I _only_ want to return matches above a certain entropy.

**Comment by plusvic** [comment]
Let's assume you want to find any string starting with "example|" followed by some high-entropy text.

```
import "math"

rule test {
    strings:
        $a =  /example\|\w*/
    condition:
        math.entropy(@a+8, !a-8) > 0.8
}

```

In this condition I'm using `@a` for determining the offset where `$a` matches, and I'm adding 8 because "example|" is 8 chars long and I want to calculate the entropy of the strings that follows, without the "example|" prefix. Similarly, I use `!a` for determining the length of the matching string, subtracting 8 for the same reason.

If your pattern starts with some non-fixed-length prefix then you can't use this trick because there is no way of knowing the offset where some portion of a regexp matches.
