### ISSUE TITLE
Yara C API Compiler Calls 'abort()' Terminating Main Programs (Error Handling)

### ISSUE THREAD

**Issue by lillypad** [VirusTotal/yara#1205]
I'm working on a little project that takes rules from sources that may or may not have rules that are working (on the internet). To do this means proceeding to run your scan with only displaying errors but not failing / exiting.

When using the rule compiler with the structure `YR_COMPILER` if any errors are encountered with the rules added using `yr_compiler_add_string`, `yr_compiler_add_file` and `yr_compiler_add_fd` functions it will fail causing `SIGABRT` closing the main program though error handling may already be provided.

Currently it appears the only work around is to create a supplemental function like the following:
```c
int yr_check_string(char *pRuleString){
  struct YR_COMPILER compiler;
  lyara_init(&lyara_t);
  int result = yr_compiler_add_string(compiler,
                                      pRuleString,
                                      NULL);
  lyara_cleanup(&compiler);
  return result;
}
```
From what I've been reading `assert` and `abort` are typically avoided in libraries so that main programs can easily handle errors without the library terminating the running process.

It seems it would be much easier to have the `YR_COMPILER` handle the error without having it call `abort()` and return the error as it already does without killing the whole compiler.

Though I found this in the documentation which doesn't make any sense to me:
![image](https://user-images.githubusercontent.com/9785864/73317747-8913b680-420d-11ea-86b8-8d9ffa19b94b.png)

Also creating a whole new `YR_COMPILER` to do the checking for you and creating and destroying it every single time to check seems a little excessive, could we make this more efficient?

Thank you :smile:

**Comment by plusvic** [comment]
When the compiler exits from `yr_compiler_add_x` with an error code, some internal data structures are left in an inconsistent state and can't be reused. This is because the syntax error can be detected when most of the rule has been already parsed and a lot information already written so some structures that work in append-only mode, this information can't be unwritten, but the compiler can't continue because it found an error, so it is not usable anymore.

The `assert` statement makes sure that the compiler is not reused after an error is returned. Certainly this `assert` could be replaced by a return code from `yr_compiler_add_x` telling you that the compiler is in an inconsistent state, and you are right when you say that `assert` should be avoided in libraries, in favor of returning error codes from which the user can recover from.

However I think it's ok to use `assert` in this specific case because it is supposed to be used for detecting situations that should never happen, invariants that are being violated, and so on. If someone ends up reusing a compiler is not because some unpredictable error, like a bad user input, an error reading from a file or something like that, is because the compiler is being used in a way that violates the allowed use pattern. This is not an unexpected but recoverable error, something the user can handle and continue with its program, it's something that you better find early while writing your program, and once you fix it, you can even turn off assertions completely because this issue won't happen again.

In resume, the only alternative in your case is creating a new compiler every time. This is something I do myself in certain systems where I want to validate individual rules.

**Comment by lillypad** [comment]
lol

**Comment by plusvic** [comment]
I'm not sure if my answer has been convincing enough, sorry for that. Let me know if you have additional concerns and I'll try to explain myself better.
