### ISSUE TITLE
invalid field name "export_timestamp"

### ISSUE THREAD

**Issue by schrodyn** [VirusTotal/yara#1230]
### Issue
PE export_timestamp missing in Yara v3.11.0
As per the documentation, https://yara.readthedocs.io/en/latest/modules/pe.html

```
export_timestamp
    New in version 3.11.0.
    The timestamp the export data was created..
```
### Steps to reproduce
(On `2020-03-09`) Download and compile https://github.com/VirusTotal/yara/archive/v3.11.0.tar.gz

Host:
```
$ uname -a
Linux hostname 4.19.0-8-amd64 #1 SMP Debian 4.19.98-1 (2020-01-26) x86_64 GNU/Linux
$ cat /etc/debian_version 
10.3
```

Log file of compilation available upon request.

```
import "pe"

rule export_test
{
    condition:
        pe.export_timestamp == 1827812126
}
```

```
$ yara -v
3.11.0
$ yara export_timestamp.yara ~/Downloads/MALWARE/
export_timestamp.yara(6): error: invalid field name "export_timestamp"
```

Affecting `3.11.0`.

Example from tests, https://github.com/VirusTotal/yara/blob/master/tests/test-pe.c#L252

**Comment by wxsBSD** [comment]
This is actually a bug in the documentation. The features you're trying to use are not in a release yet, but are incorrectly documented as being added in 3.11.0 instead of 3.12.0. I'll get a fix up for this. In the meantime I highly suggest using the version specific documentation: https://yara.readthedocs.io/en/v3.11.0/modules/pe.html (notice the v3.11.0 in the URL).

**Comment by wxsBSD** [comment]
On a sidenote, I have no idea how readthedocs works but having the link point to "latest" which appears to be whatever is in master is confusing for users, given how long things can sit in master before being released. Is it possible to have the link point to whatever the latest version is instead of whatever is in master?

**Comment by plusvic** [comment]
"latest" is always the last commit in master, what I've done is
changing the default version to "stable" which seems to match the highest
version number among the tags you have in the repository. So, now you
always land in the most recent release.

**Comment by schrodyn** [comment]
Thanks everyone!
