### ISSUE TITLE
Provide XOR keys in results

### ISSUE THREAD

**Issue by malvidin** [VirusTotal/yara#1235]
When a YARA rule matches a string with an `xor` keyword, the XOR key cannot be determined.
I could not find a way to extract the original string value from the compiled rule, or the returned match strings.

```
import yara

a_orig= b"AAAA" 
mydata = b"BBBB"

yr = yara.compile(source="rule test_xor {strings: $a_xor=\"AAAA\" xor(0x01-0xff) condition: all of them}")

yml = yr.match(data=mydata) 
for ym in yml:
    if a_orig in ym.strings:
        print("Found original string in match strings")
    for offset, label, match in ym.strings:
        key = None
        if a_orig == match:
            key = 0
        else:
            keys = set([a ^ b for (a,b) in zip(a_orig, match)])
            if len(keys) == 1:
                key = keys.pop()
        if key is not None:
            print(f"XOR key for {label} is {key}")
if key == 3:
  print("Expected key found")
```

**Comment by wxsBSD** [comment]
I can understand wanting to get the XOR key back, but you can always calculate it if needed, without having to expose the original string value in the compiled rule. I've implemented this before, and it is doable if you're willing to hardcode the plaintext from your rule into your python code for handling the match. Just check to see if the rule that matched is the one you want (`test_xor` in your case), then find the matched string you want (`a_xor` in your case) and calculate the xor key for each of the matched instances. Yes, it requires you to hard code the plaintext in your code (`AAAA` in your case) but it will work.

What you're asking for is to either expose the plaintext of the string in the compiled rule (which is not easy since some types of strings are actually compiled into an automaton and the plaintext is thrown away) or to make a special exception for returning a match plus "extra" data specific to that match (the xor key in this case). Given that you can always calculate the xor key on a match if you are willing to hard code the plaintext from the rule in your code, I'm not sure the value this brings is worth the internal complexity it would introduce.

**Comment by malvidin** [comment]
I do not want to  hardcode plaintext into the python code, I'd much rather have it in the same rule.

I think I can work around it by making a callback function that appends an `xorkey` to the metadata based on another metadata value that contains the plaintext.

Do you have any recommendations, or is this a sufficient workaround to close this issue?

```
import re
import yara


def xor_meta_callback(data, first_match_only=True):
    xor_info = []
    xor_pt = {re.sub(r'xor_pt_', '$', k): v for k, v in data['meta'].items() if k.startswith("xor_pt_")}
    if len(xor_pt) != 0:
        key = None
        for offset, label, match in data['strings']:
            if label not in xor_pt:
                pass
            if xor_pt[label] == match:
                key = 0
            else:
                keys = set([a ^ b for (a, b) in zip(a_pt, match)])
                if len(keys) == 1:
                    key = keys.pop()
                    xor_info.append((offset, label, key))
                    if first_match_only:
                        data['meta']['xorkey'] = key
                        return yara.CALLBACK_CONTINUE
    data['meta']['xor_info'] = repr(xor_info)
    return yara.CALLBACK_CONTINUE

a_pt= b"AA\nAA"
mydata = b"BB\tBBAA\nAA"
myrule = r'''
rule test_xor
{
  meta:
    test = "value"
    xor_pt_a_xor = "AA\nAA"
  strings:
    $a_xor="AA\nAA" xor
  condition:
    all of them
}
'''

yr = yara.compile(source=myrule)
yml = yr.match(data=mydata, callback=xor_meta_callback)

print(yml[0].meta)
```
