### ISSUE TITLE
Unify YR_SCANNER and YR_SCAN_CONTEXT for v4?

### ISSUE THREAD

**Issue by hillu** [VirusTotal/yara#1243]
Hi Victor,

since YR_SCANNER and YR_SCAN_CONTEXT are essentially the same type, wouldn't it make sense to get rid of one of them?

Cheers,
-Hilko

**Comment by plusvic** [comment]
That was made in purpose because they are two different concepts, YR_SCANNER represents a scanner, something that you use to scan files or memory buffers and YR_SCAN_CONTEXT represents the state of a scan. In the future YR_SCAN_CONTEXT may be a member of YR_SCANNER and each of them may have additional members that don't apply to both. The fact that they are currently the same thing is just an implementation detail.

**Comment by hillu** [comment]
Ah, I see. I'll be using a separate wrapper type for go-yara v4 then. :-)
