### ISSUE TITLE
For xor match'ed strings, include the xor key in the returned match object.

### ISSUE THREAD

**Issue by tlansec** [VirusTotal/yara#1319]
Hello,

The "xor" keyword is an excellent addition to YARA and has made writing rules for xored strings much easier. However when triaging the matches, a common process (at least for me is):

* Run my rules on the file
* See a xor match
* Manually check what the key was for that xor match
* Xor the entire file with that key to see other interesting data that was encoded /w the same key.

To expedite this process, it would be useful if the string match objects for xored strings included the key which was used to generate the match.

I appreciate this may be non-trivial to do, but thought i'd raise it just incase.

Thanks,
Tom

**Comment by wxsBSD** [comment]
The problem is the key is actually not known to YARA after the rule has been compiled. We actually throw the key away and recalculate it when we verify a match happens. There is also no good way to get the key back out to the caller once a match has been verified.

My suggestion is to automate this with the python-bindings. It sucks to have to do it this way but I don't have a better answer right now.

**Comment by tlansec** [comment]
I suspected this would be the case. 

Can probably close as "won't/can't do" in that case.
