### ISSUE TITLE
support the use of function calls in the "for any of" construct

### ISSUE THREAD

**Issue by evilsocket** [VirusTotal/yara#1376]
According to the documentation the [for any of](https://yara.readthedocs.io/en/v4.0.2/writingrules.html?highlight=%22for%20any%20of%22%C3%B9#applying-the-same-condition-to-many-strings) construct supports a boolean_expression. However this is only true for simpler inline expressions. A module function call is not supported at the moment. 

For instance, in a module we're developing we have something like:

```c
begin_declarations;
  declare_function("has_api", "s", "i", has_api);
end_declarations;
```

and we tried to use it this way:

```yara
rule some_test_rule {
    strings:
        $api_name0 = "doSomething"
        $api_name1 = "doNothing"

    condition:
        for any of ($api_name*) : ( our_module.has_api($) )
}
```

This throws the error:

```wrong arguments for function "has_api"```

I tried to add a debug printf of ```actual_args_fmt``` [in the piece of code that generates that error](https://github.com/VirusTotal/yara/blob/master/libyara/parser.c#L305), and I get ```"b"```, so ```$``` is somehow a boolean argument (?)

Tested on 4.0.2 and master.

**Comment by plusvic** [comment]
The issue is not actually related to the `for` loop, you can't do this neither:

```yara
rule some_test_rule {
    strings:
        $api_name0 = "doSomething"
        $api_name1 = "doNothing"
    condition:
        our_module.has_api($a) or our_module.has_api($b)
}
```

So, the problem is that you can't pass a string defined in the `strings` section to a function that expects a string. Those are two different types of strings actually. The former are patterns, the latter are string variables or literals. In retrospect, the `strings` section would be better named `patterns`, that would avoid confusion, but it's too late to rename it. In resume, ` $api_name0` and ` $api_name1` are not the kind of strings that you can pass to a function that expects a string.

**Comment by evilsocket** [comment]
did you close this because it's not strictly related to "for any of" or because support for variables as module functions arguments will not be implemented?

**Comment by plusvic** [comment]
I close it because support for passing strings (those defined in the `strings` section) as function arguments won't be implemented.
