### ISSUE TITLE
Apply the "condition" items using the same order in which they were specified

### ISSUE THREAD

**Issue by aprokofiev** [VirusTotal/yara#1415]
Please consider the following example (not an actual rule):

```yar
import "pe"

rule Test
{
	strings:
		$s = /[A-F0-9]{100}/ wide
	condition:
		pe.is_32bit() and filesize < 10MB and $s
}
```
It takes almost 50 seconds for **Yara** to scan the 500MB file on my VM which is perfectly understandable. **Yara** even warns us that `$s` in rule `Test` is slowing down scanning.

However the thing is - it is not a 32bit PE file and its size is way larger than 10MB, therefore there was no need to scan it in the first place.

We are adding new rules rather frequently facing the snowball-slowdown effect.

By applying any additional items to the `condition` section I always thought that it will help to reduce the load:

1. `pe.is_32bit()`? No, skip it.
2. `filesize < 10MB`? No, skip it.
3. now we scan for `/[A-F0-9]{100}/ wide`

Is it possible to implement it this way?

**Comment by wxsBSD** [comment]
This comes up from time to time and is not how things work. All strings are searched for and then conditions are evaluated, as you have just found out. This may seem counter intuitive but there is a good reason for this. With the way string matching is done all strings are searched for in a single pass, all at once. Most of the time there are many rules being used at once and chances are at least one string will need to be scanned for if we were to do your suggestion. As soon as you have to search for one string you might as well search for them all because you want to do only a single scan and you can do them all at once.

Your example makes sense in isolation but is not the common case when using yara. Further, to implement your suggestion would require multiple passes through the data.

**Comment by aprokofiev** [comment]
Is it possible to check those conditions first which already have their values resolved and can be checked instantly?

Those with `filesize`, **PE** attributes (you'll still have to gather this information eventually and it will not require any additional pass), etc.

Otherwise so far it looks like any huge file will be scanned, even if all the rules are against it using their set of conditions.

**Comment by wxsBSD** [comment]
It's not possible to check some of the conditions first and then decide to do the string searching. Even if it were possible, the likelyhood of ALL the rules having carefully controlled conditions such that we can do this is effectively zero in the real world.  The searching scales with the size of the input file, not the number of strings. As soon as one of the strings needs to be searched for you might as well search for all of them because having 1 string or 10000 strings is not a significant difference with the way the searching works.

In your scenario where you have carefully controled ALL the rules it makes sense to do what your suggesting but in the common case where you have LOTS of rules with various conditions that likely don't exhibit the behavior your using, the fact is one string will always require searching.

For your specific case I would suggest pre-filtering the files based upon size or to listen to the compiler when it says your string is slowing down scanning. The amount of perf hit your going to get is primarily based upon the size of the file when that warning comes up.

**Comment by aprokofiev** [comment]
I see. It looks like nowadays if we receive ~100 000 files, they all will be scanned for strings (including the regexps) even if conditions could filter out half of those files.

Thank you. This helped me to understand that all external modules are there to filter the output, not to reduce the input, which is rather frustrating, but oh well.

Since we heavily rely on **Yara** in our filtering process, it would be better for us to implement something else. The pre-filtering stage, however, is still an option.

Thank you for your time, @wxsBSD.

**Comment by simonhf** [comment]
> The searching scales with the size of the input file, not the number
> of strings.

I agree with this idea in general. But I wonder if nevertheless YARA could be optimized further in a way that would both work for the common use case and the use case of @[aprokofiev](https://github.com/aprokofiev), and other use cases which YARA can't currently handle?

I've been getting into YARA internals recently and have made a couple of PRs for various things, e.g. testing scanning memory divided into blocks (in `master`), and introducing a non-blocking API (in branch `non-blocking-api`). This has given me some ideas which I will try to elaborate on here:

Let's imagine the following example rule which contains both a string to search for *and* YARA hash module usage:
```
import "hash"

rule Test
{
  strings:
    $s = /[A-F0-9]{100}/ wide
  condition:
    (filesize < 10MB and $s) or
    (hash.md5(0, 1023) == "dcc824971a00e589619ba0c0bba41515" and
    hash.md5(1024, filesize - 1024) == "ab56b4d92b40713acc5af89985d4b786" and
    hash.md5(filesize - 1024, filesize) == "ef123c9b3d66ac42b3ba2232b4f5cf7f")
}
```
Now let's imagine this rule applied to a 500MB file:

By default YARA will divide the 500MB file into 1 memory block of 500MB. However, YARA is designed so that its string matching and modules also work if the file is divided into a sequence of smaller blocks, so for the sake of the example, let's imagine 500 memory blocks of 1MB. And yes, YARA can handle strings straddling two memory blocks :-)

So at runtime the following happens when scanning the 500MB file:

 - Loop over 500 memory blocks searching for all strings.
 - Start interpreting the condition business logic:
   - Module loops over 500 memory blocks for MD5 1 (early exits after 1st block).
   - Module loops over 500 memory blocks for MD5 2.
   - Module loops over 500 memory blocks for MD5 3 (only using last block).

There are a couple of disadvantages with this approach *if/when* using YARA modules:

 1. The 500MB file is looped over multiple times; inefficient; thrashing the CPU memory cache.
 2. The entire 500MB file has to be available at scan time. If this wasn't the case and you want to use YARA to incrementally scan each block of the 500MB file as it's e.g. passing across a network then the multiple looping over the blocks creates issue (a) inefficient resource usage because the file needs to be saved to disk or buffered in memory in its entirety before it can be scanned, and issue (b) a delay to start scanning during which the file is being 'received'.

How to refactor YARA to workaround these disadvantages?

Currently YARA loops over **x** memory blocks **y** times (one loop for searching strings in any rule, and up to one loop for each module condition used (if the module uses the `foreach_memory_block(){ ... }` module macro), and interprets the condition business logic **once**.

What if YARA was changed so that YARA loops over **x** memory blocks only **1** time (for each memory block searching for strings in any rule, *and* letting any module access the same block at the same time), and interprets the condition business logic **x** times (once for each memory block)? This would solve both disadvantages above including 2a and 2b, because only the next single block of the 500MB file need be available at any time during the scanning process.

But also, it would potentially solve the disadvantage of the case @[aprokofiev](https://github.com/aprokofiev) is suggesting where less rules are being used, and all rules have something like `filesize < 10MB` limiting the amount of file needed to be scanned. If so, YARA would not necessarily need to loop over all x memory blocks and could 'early out' of the single loop over all the memory blocks of the file (because eventually for a file memory block, there might no rule condition business logic left to execute)?

From a coding perspective this all seems doable. But I'm not sure if it's doable and backwards compatible with existing YARA rules and modules. Definitely the modules would need to be refactored to remove the blocking `foreach_memory_block(){ ... }` loop. But still not sure if existing YARA rules could be coerced to work with such a new scheme.

I'm hoping that YARA gurus can chime in here and offer constructive criticism :-)

**Comment by plusvic** [comment]
@simonhf I'm afraid your proposal is going to be hard to implement. Take the case of the `hash` module as an example. This module iterates over all the memory blocks each time a hash function is invoked in a condition. The hash function needs to read all the relevant data, that's why it needs to iterate over the blocks. In order to compute multiple hashes in a single pass, with varying starting offsets and lengths, the `hash` module would need to keep a list of all the hashes that need to be calculated, and the logic the `hash` module would more complicated because it would need to track all the hashes at the same time. And not only the `hash` module would be more complicated, the API between YARA and the modules would be more complex also, because it needs a way for telling the module, hey, I want you to execute all these function calls, with all these arguments... but don't execute the calls yet, you will have a single opportunity for running all the calls so that the data is accessed once.

**Comment by simonhf** [comment]
> the logic the `hash` module would more complicated because it would
> need to track all the hashes at the same time

Yes, I agree. Currently the modules store their state on the stack, and operate one after the other. So the stack only ever has one state stored on it. This is nice and lightweight, but on the negative side... forces multiple passes at run-time, and the entire file to scan must be in memory, even it it's multiple GBs in size for a single file.

I'm not sure the best way to calculate the memory overhead for storing module state. Everywhere where I've written **e.g.** then I'm just guesstimating / brainstorming:

Let's imagine that the state for each module call is **e.g.** 64 bytes and we have **e.g.** 50k module calls in all rules, but for a particular memory block being scanned maybe only max **e.g.** 10% of module calls need be active? That'd be 0.3MB memory for state per file scanned, or with max **e.g.** 2,500 active files that'd be 0.75GB memory for state for all concurrent files scanned.

Depending upon what the **e.g.** values are above, then the total memory used for state could be relatively small, or also in the multiple GBs size or bigger range. As a newbie to YARA then I'm not sure about what types of volumes of rules users pump through YARA. I tried downloading 20k publicly accessible `.yar` files containing 76k rules, of which about 45k rules used modules, which is how I got to the 50k module calls. However, I'm not sure how to estimate the max amount of those module calls which would be active at any time on a particular memory block being scanned. Maybe somebody using lots of rules with YARA on lots of files could instrument YARA to figure out what is realistic?

> not only the `hash` module would be more complicated, the API between
> YARA and the modules would be more complex also

Yes, I agree. This would make YARA operate much more like an event based system, like Golang with co-routines, etc. Without better estimates regarding the state memory overhead, then the complexity might not be worth it, if the state memory needed at run-time is prohibitively large? How to determine if it would be prohibitively large?
