### ISSUE TITLE
Duplicated identifier

### ISSUE THREAD

**Issue by mark260486** [VirusTotal/yara#1442]
Hi, community!

I'm refactoring your index_gen.sh to Powershell cause i need to do updates and compile rules on the Windows. All look good until compiling started and i got error about duplicated rules. I compared results indexes in Meld and find difference in rules order. Is it critical to compiling?

Powershell code - https://pastebin.com/GayKeA8k
Powershell created Index - https://pastebin.com/p9HHVhuH
Original index - https://pastebin.com/wVYnbvQ7
Error screenshot in the attachment.
![2021-02-03_12-56](https://user-images.githubusercontent.com/49118755/106732235-82d6c800-6621-11eb-9ddc-0ff7b1a80369.png)

**Comment by plusvic** [comment]
I think this issue was intended for some other repository containing YARA rules, am I right?

**Comment by mark260486** [comment]
Hi, @plusvic! Thank you for the reply. 
No, i tested only with this ruleset - https://github.com/Yara-Rules/rules

**Comment by plusvic** [comment]
But what's the issue exactly?

**Comment by mark260486** [comment]
Ruleset indexes generated with index_gen.sh and my PS script are pretty the same. I have necessary to use PS for index generate. But Yara rule compiler cannot compile ruleset with PS generated index.

**Comment by h3x2b** [comment]
Hello Victor, 
yara ends with error if in the set of rules being compiled there is more than 1 rule with the same name.
It would be nice to have some parameter/option to be able to suppress/ignore this error and for example take just the first rule in the set with the same name.

This often happens if you try to compile ruleset compiled from more sources - it can easily happen that some signature is there twice with the same name.

For example if you take ruleset from https://github.com/Yara-Rules/rules (agregator of yara rules) and combine that with the ruleset for example from Florian Roth https://github.com/Neo23x0/signature-base or kevthehermit https://github.com/kevthehermit/YaraRules you will find that some of the rules overlap and yara compilation will end with error.

**Comment by wxsBSD** [comment]
I'm not sure introducing an option to say "first rule with a duplicate name wins" is a good idea here. Other rules may rely upon the behavior of the second rule (the one we threw away) and may now not work as they are intended.

When running YARA rules from third-party sources one must take care to review and carefully curate the rules.

**Comment by plusvic** [comment]
I agree with @wxsBSD, I think such an option would do more harm than good in the long term. 

If you want to compile together rules coming from multiple sources that may contain colliding names, a good solution is using namespaces. A different namespace for each of your sources guarantees that even if two rules have the same name they will be treated as different rules.

**Comment by mark260486** [comment]
So what should i do? :)
I use only one ruleset from one source.

**Comment by plusvic** [comment]
Can you share here the index.yar file generated by your script?

**Comment by mark260486** [comment]
Sure, it is in original post

**Comment by plusvic** [comment]
The index.yar generated by your script contains duplicated lines. The same files are being imported twice, that's why you get errors about duplicated identifiers.

**Comment by rootkiter** [comment]
Whether a judgment logic can be added to solve multiple loading conflicts. such as：

```
if didnot include "common.yara"
   include "common.yara"
fi 
```

or

```
include_if_not "common.yara"
```
