### ISSUE TITLE
performance optimization from deduplicating identical link targets?

### ISSUE THREAD

**Issue by abathur** [VirusTotal/yara#1469]
I'm not sure if it's feasible to address within the scanner design (nor if the savings for ~normal scans are significant enough to make it worthwhile), but I noticed that yara seems to separately scan files that are all symlinks to the same target.

In my case this was ~100+ coreutils symlinks to the same binary. A direct scan of just the big coreutils binary takes about 20-30ms, while the whole set takes about 250ms with default threads, and around 600ms with `threads=1`.

**Comment by plusvic** [comment]
I'm afraid this it not worthwhile. In order to prevent rescanning the same file again you would need to track all the files that you have already scanned, which means more memory usage. Also, for every scanned file you need to perform a lookup for verifying that the file has not being scanned, that's additional time. So at the end you are adding complexity, more memory usage, and a bit of additional time in all scans for a very small gain.
