### ISSUE TITLE
4.1: Extended iterator interface should be made (mostly) backwards compatible

### ISSUE THREAD

**Issue by hillu** [VirusTotal/yara#1476]
go-yara implements a wrapper around `yr_{rules,scanner}_scan_mem_blocks` and the `YR_MEMORY_BLOCK_ITERATOR` type. Unfortunately, the changes made in 4.1.0 make it crash because the `file_size` function does not get initialized, see https://github.com/hillu/go-yara/issues/88.

There's another subtle issue related to the `last_error` field that now needs to be explicitly set by the iterator functions.

Increasing the struct size meas an ABI incompatibility with YARA 4.0, so I'd advise to bump the SONAME. The addition of `last_error` that needs to be set by the iterator (at least according to the comment in `types.h`) means an API-level incompatibility: Applications or libraries (such as go-yara) that wish to support both YARA 4.0 and 4.1 can't do so without some `#ifdef`fery.

I think we can do without the `last_error` field, for example by having `first` and `next` signal the "not ready" condition back by returning `(YR_MEMORY_BLOCK*) -1`.

**Comment by plusvic** [comment]
Returning `-1` from `first` and `next` is not enough, either the scanner or the iterator must remember that the last call to `first/next` resulted in a "not ready" error, so that the next call to `yr_scanner_scan_mem_blocks` can retry the operation.

I'm going to bump the SONAME as advised. In fact, I'm thinking about not passing `--version-number` to `libtool` anymore and use `--release` instead. This would make all new releases (even minor ones) binary-incompatible with previous releases. Any thoughts?

**Comment by hillu** [comment]
@plusvic Regarding the SONAME: With the current development speed, I wouldn't really have a problem with minor versions (e.g. 4.0, 4.1, 4.2) being treated as ABI-incompatible by default. Just please don't do this for every patchlevel change (e.g. 4.0.3, 4.0.4, 4.0.5).

**Comment by plusvic** [comment]
Fixed the SONAME issue in 3f179ac2a2e13349ea69d6de3f4ceb65b32265fd, allowed `file_size` field in `YR_MEMORY_BLOCK_ITERATOR` to be `NULL` in 98b4dd317324e8f01ec59793ebf85291fc7db162.

Also 98b4dd317324e8f01ec59793ebf85291fc7db162 makes clearer that `last_result` can be initialized once and not touched again by `first` and `next` functions.

**Comment by hillu** [comment]
While I was looking at the code to suggest what a different approach might look like, I stumbled across the `foreach_memory_iterator` macro that is heavily used in modules. This should also take into account the `ERROR_BLOCK_NOT_READY` state, shouldn't it?

**Comment by plusvic** [comment]
Good catch. 

Certainly `foreach_memory_iterator` should take into account that the iterator can return a `NULL` memory block and `ERROR_BLOCK_NOT_READY`, which doesn't means the end of the iteration, but that the block is not ready yet. One solution is making `foreach_memory_iterator` to keep polling the iterator until it stops returning `ERROR_BLOCK_NOT_READY`, however this implies that the async scanning API won't be really async. It will be async only during the first iteration over the memory blocks (the one done by the scanner), but subsequent iterations caused by `uintXX()` functions in the rule, or by modules using the `foreach_memory_iterator` won't be async. 

For the time being, I think that we can assume that the iterator won't never return `ERROR_BLOCK_NOT_READY` when you try to iterate it for a second time. In other words, once you do the first iteration, the iterator should cache the blocks so that it doesn't need to perform costly operations that may causes a `ERROR_BLOCK_NOT_READY` again.

It's going to be very difficult to get rid of this requisite. For the `uintXX()` functions it can be done, there are ways to implement these functions without iterating over the blocks again, but for the modules using `foreach_memory_iterator` it's more difficult. 

@simonhf, as the main promoter of the async API you should be aware of this ^^^.

**Comment by hillu** [comment]
The loops could be changed to wait (using an exponential back-off scheme) if the iterators signal that they are not ready…

**Comment by plusvic** [comment]
That was my initial intention, but it requires a new function for doing the pollin, which returns only when the iterator has stopped returning `ERROR_BLOCK_NOT_READY`. But it doesn't solve the fundamental problem mentioned above, so I think I'll leave it as is for the time being.
