### ISSUE TITLE
Scan folder program cannot exit

### ISSUE THREAD

**Issue by lokippc** [VirusTotal/yara#1481]
![image](https://user-images.githubusercontent.com/4179028/115005286-4bff1700-9eda-11eb-8927-af27823910da.png)
When I set the timeout through the-a parameter, the timeout will cause the program not to exit.
Reason:
After the timeout, all 32 consumer threads have exited. The thread that scans the file will get stuck in the function file_queue_put

**Comment by plusvic** [comment]
Good catch, under certain circumstances the main thread could get stuck at the `file_queue_put` function. This is harder to reproduce by scanning a directory recursively, because `scan_dir` also takes the timeout into account and breaks its loop when the timeout is reached. So, in order for this to happen the following conditions must me met:

* The queue is full when the the timeout is reached
* All the scanning threads finish due the timeout leaving the queue full
* When the timeout occurs `scan_dir` has already checked for the timeout but has not called `file_queue_put` yet, so it enters `file_queue_put` before checking for the timeout first. `file_queue_put` will block because the queue is full and nobody is removing files from it.

This is easier to reproduce using the `--scan-list` option, because `populate_scan_list` doesn't check for the timeout at all.

**Comment by lokippc** [comment]
Note that it is on the win32 platform。

**Comment by plusvic** [comment]
Well, actually the problem is present in all platforms, but in Windows is worse because the Windows implementation for `scan_dir` was not taking the timeout into account.
