### ISSUE TITLE
Fast Match/Patterns (Is it Possible)

### ISSUE THREAD

**Issue by c3rb3ru5d3d53c** [VirusTotal/yara#1500]
Hello yara devs,

I wanted to probe to see how challenging it would be to implement a `fast_match` keyword.

```yara
rule test {
     strings:
         $mz_magic_0 = "MZ"
         $other_stuff_0 = "other stuff"
     condition:
         fast_match($mz_magic_0 and filesize < 1MB) and
         $other_stuff_0
}
```

Suricata and other IDS utilities use `fast_pattern`, how challenging would it be to implement a `fast_match` keyword to match on specific items before others.

If it's possible, it would result a significant increase in performance.

**Comment by plusvic** [comment]
Which behavior do you expect from `fast_match`?

**Comment by c3rb3ru5d3d53c** [comment]
The expected behavior would be that, yara will check the result `fast_match` first before any other check in the `condition`. If the `fast_match` check returns `false` all further checks in the `condition` are ignored.

**Comment by plusvic** [comment]
Now I get the idea, but in case we ever implement something like this, I would prefer doing it in a transparent way. I mean in way that you don't need to tell explicitly which portion of the condition should be evaluated first. This is something that could be done. For example, in a condition like `$mz_magic_0 at 0 and filesize < 1MB and $other_stuff_0` it's possible to infer that `$mz_magic_0 at 0 and filesize` can be evaluated first without having to scan all the data looking for `$other_stuff_0`, something like `fast_match` makes the implementation easier, but puts the burden on the rule writer.

Anyways, the reason this hasn't been implemented yet is that it won't bring any performance gain in mosts of the cases, because as soon as you have multiple rules and a single one needs a full data scan searching for some string, your performance gain is evaporated. The gain can be noticeable in cases where you have a single rule, or when all your rules have some term in the condition that can decide the outcome without having to scan the data, but that's rarely the case.
