### ISSUE TITLE
How to change / update external variable of compiled rules at runtime?

### ISSUE THREAD

**Issue by dmknght** [VirusTotal/yara#1566]
Libyara Version: 4.0.5-1 (Debian-testing based distro)
Language: Nim lang with libyara binding. This is a custom binding.

Problem: I want to do filename matching, which is similar to #202 and #269. By now I'm using `yr_rules_load` to load *compiled rules*. I haven't tried load text-based rules. My rule:
```
rule test {
  condition:
    filename == "/tmp/testfile"
}
```
Compile command: `yarac -d filename=foo test.yar sig.db`
My scan file function:
```
proc scanFile(scanner: ptr YR_SCANNER, fileName: string, user_data: ptr CALLBACK_ARGS, file_count, err_count: var int) =
  if not fileExists(fileName):
    return
  else:
    user_data.file_path = fileName
    file_count += 1
    discard yr_rules_define_string_variable(scanner.rules, "filename", fileName)

    # Print value of extenal variables in rules
    # echo "Extern-var: ", scanner.rules.externals_list_head.identifier, " value: ", scanner.rules.externals_list_head.value.s

    let scan_result = yr_scanner_scan_file(scanner, fileName)
    if scan_result != ERROR_SUCCESS:
      err_count += 1
```
The idea: When i call the scan directory, this function uses walk directory method to get file name. For scan only 1 file, the file name is passed directly to the scanFile function. Then the external variable will be *changed* by `yr_rules_define_string_variable(scanner.rules, "filename", fileName)`. It should apply to all rules that have `filename` variable.

Test result: With the simple echo command (which is commented in the code above), it shows result `Extern-var: filename value: /tmp/testfile`. If I do the scan directory, the variable's value changes. Match: 0.

However, if i compile yara rule with command: `yarac -d filename=/tmp/testfile test.yar sig.db`, result shows matched:
```
Detected:
  Rule: test
  Path: /tmp/testfile
Signatures: 1
Dir scanned: 0
File scanned: 1
Error: 0
```

Expected: Rule matches no matter what value of external variable is during runtime.

So the issue could be:
1. Rule's variable didn't update during runtime?
2. I am using wrong function / API which is changing wrong variable / wrong struct

So I create this issue and hope dev team can fix this, or point me the right direction.
Thanks in advance!

**Comment by dmknght** [comment]
I think i found the solution. Likely the `scanner.rules` values weren't changed by the code. IDK if it is the problem of binding or the yara design but using `yr_rules_scan_file` instead of `yr_scanner_scan_file` solved my problem.
```
proc scanFile(rules: ptr YR_RULES, fileName: string, user_data: ptr CALLBACK_ARGS, file_count, err_count: var int) =
  if not fileExists(fileName):
    return
  else:
    user_data.file_path = fileName
    file_count += 1
    let meta_file_name = splitFile(fileName)

    discard yr_rules_define_string_variable(rules, "file_path", fileName)
    discard yr_rules_define_string_variable(rules, "file_name", meta_file_name.name)
    discard yr_rules_define_string_variable(rules, "file_dir", meta_file_name.dir)
    discard yr_rules_define_string_variable(rules, "file_ext", meta_file_name.ext)

    let scan_result = yr_rules_scan_file(rules, fileName, 0, callback_scan, user_data, 1000000)
    if scan_result != ERROR_SUCCESS:
      err_count += 1
```

**Comment by plusvic** [comment]
The problem was this line:

 `yr_rules_define_string_variable(scanner.rules, "filename", fileName)` 

You can't modify the rules hold by the scanner, the scanner object represented by a`YR_SCANNER` should be treated as an opaque structure, you shouldn't pass `scanner.rules` to any other function expecting `YR_RULES`. All the fields in the `YR_RULES` structure are for YARA's internal use, unless they are explicitly documented as part of the API. The scanner should be manipulated only with `yr_scanner_xxxx` functions, and rules should be manipulated with `yr_rules_xxxx` functions.

If you have a `YR_RULES` structure you can use `yr_rules_define_string_variable` and `yr_rules_scan_file`, if you have a `YR_SCANNER` you can use `yr_scanner_define_string_variable` and `yr_scanner_scan_file`, but you can't mix both worlds.

When you call `yr_rules_define_string_variable(scanner.rules, "filename", fileName)` you are modifying the variable associated with `YR_RULES`, but then you call  `yr_scanner_scan_file(scanner, fileName)` and you are using the variables associated with `YR_SCANNER`. Each scanner has its own set of variables with their respective values, independently from the variables associated to `YR_RULES`.

**Comment by dmknght** [comment]
@plusvic thank you for your answer. It answered my all questions ^^. And i didn't notice the `yr_scanner_define_string_variable`. Well by now my code works perfectly. Thank you a lot :D
