### ISSUE TITLE
Allow XOR on byte sequences or fix bug in XORed \x representation in strings

### ISSUE THREAD

**Issue by Neo23x0** [VirusTotal/yara#1643]
I'd like to search for XORed byte sequences and couldn't find a nice way to do that. 

```
      /* not possible */
      $x0 = { E9 6C 0A 01 01 C4 56 8C ED 52 52 84 66 F9 01 8C } xor
      /* not working */
      $x1 = "\xE9\x6C\x0A\x01\x01\xC4\x56\x8C\xED\x52\x52\x84\x66\xF9\x01\x8C" xor
```

The $x1 doesn't work, although I believe that it should. It could be a bug or something that I miss. 

Sample to test it on: 
https://www.virustotal.com/gui/file/601a02b81e3bd134c2cf681ac03d696b446e10bf267b11b91517db1b233fec74/content/hex

![Screenshot 2022-01-27 at 19 18 11](https://user-images.githubusercontent.com/2851492/151419721-5790bc27-f713-44a2-a701-77107b5557e3.png)

I've used YARA 4.1.3 for my tests.

**Comment by wxsBSD** [comment]
I just did some testing and this does indeed seem like a bug, but based upon my testing it only happens if the entire string is escaped. I'll see if I can dig a bit deeper tonight...

**Comment by Neo23x0** [comment]
Thanks for the review. 

Based on your testing, I tried to find an XORed version of that byte sequence that contains many ASCII characters. 

```
$x1 = "W\xD9wnn2\xc3\xF9\x5B\xBF\xBF\xF1\xD3gn\xF9" xor
```

I tried shorted version of that string and it also fails. 

```
$x2 = "W\xD9wnn2" xor
```
```
$x2 = "\xc3\xF9\x5B\xBF\xBF\xF1\xD3gn\xF9" xor
```
```
$x2 = "wnn2\xc3" xor
```

**Comment by Neo23x0** [comment]
The rule that I tried to improve was one from a report of a German authority

![Screenshot 2022-01-28 at 09 44 58](https://user-images.githubusercontent.com/2851492/151515307-1a2f7631-d167-4211-889f-fe115135f72d.png)

https://www.verfassungsschutz.de/SharedDocs/publikationen/DE/cyberabwehr/2022-01-bfv-cyber-brief.pdf

**Comment by wxsBSD** [comment]
Upon closer inspection I don't think is a bug.

The bytes from the file are `EA 6D 0B 02 02 C5 57 8D EE 53 53 85 67 FA 02 8D`.

The string you are searching for is `E9 6C 0A 01 01 C4 56 8C ED 52 52 84 66 F9 01 8C`.

If we xor the first byte from the file (`0xEA`) with the first byte from your search string (`0xE9`) we get a key byte of `0x03`. Repeating for the next byte (`0x6D` and `0x6C`) we get a key byte of `0x01`, so YARA is not going to find it because YARA is only able to search for a single byte key across your entire string, and the key byte is changing in your case.

Also, I haven't read the report but the description of that rule says it is looking for a sequence of bytes generated by some ADD/SUB encoding routine, and they generated all the possible values from it. This is not an xor encoded blob that they are searching for.

**Comment by Neo23x0** [comment]
Oh, my. I should have XORed it myself. Since every byte is just one decimal value lower than the other I assumed that this would be a simple 1 byte XOR without confirming it. Sorry for the confusion.
