### ISSUE TITLE
Slow scanning

### ISSUE THREAD

**Issue by zagge-cgeo** [VirusTotal/yara#1646]
When using yara with following rule 

```
rule lotsofdots  {
   strings:
     $ = /foobar\.{128,}foobar/
   condition:
     all of them
}
```

to scan the sample e8fa826ce434a9b4a9c52198579f286c available on virustotal  it takes over 30 minutes on my i7 to finish.

The prefix/suffix foobar is not in the sample. There is no warning about slow scanning when using the above rule.

**Comment by wxsBSD** [comment]
I'm a bit out of my league on this but it is matching on all the `.` bytes at the end of the file. From my brief reading of the way atoms are extracted out it is searching for both `foob` and `....` simultaneously. Because there are so many `.` bytes at the end of the file the performance becomes terrible. I would have thought the atom selection process would have thrown out `....` as an option, but it doesn't appear so.

The atoms that end up being selected look like `OR(2E2E2E2E,666F6F62)` (that is from `yr_atoms_tree_node_print()`) and `_yr_atoms_choose()` is selecting the `....` atom when it should arguably be selecting the `foob` one. I'm still digging a bit (mostly because I'm out of my league and want to learn a bit here) to see if I can adjust the selection algorithm to avoid this situation.

**Comment by wxsBSD** [comment]
I put up a PR which attempts to address this issue, but I have no idea if it is the right thing to do or not (or if I even did it correctly). As discussed in the issue the idea is to encourage slightly better atom selection by penalizing the atom when all the bytes are identical.

This does make the performance of your rule with your test file significantly better as it ends up using `r...` as an atom. However, it is still possible to write a terribly performing regex in your example, but that will always be the case if you use `\.{128,}` in your regex. For example, this performs terribly: `$a = /\x2e\x14\x00\x00\.{128,}/` on the example given but I'm not sure we can do much about it?
