### ISSUE TITLE
Cannot match unicode file path

### ISSUE THREAD

**Issue by hmn91** [VirusTotal/yara#1775]
Hi, I am using yara-python v4.2.3 with python 3 on Windows. When scanning unicode file path, I get "could not open file" error.
Here is my code:
``` 
rules = yara.load('compiled_rules.bin')
for root, dirs, files in os.walk("D:/"):
    for file in files:
        try:
            print("Scanning: ", os.path.join(root, file))
            rules.match(os.path.join(root, file), callback=match_callback, which_callbacks=yara.CALLBACK_MATCHES)
        except yara.Error as e:
            print("Yara Exception: ", os.path.join(root, file), ' ---> ', e)
        except Exception as e:
            print("Exception: ", os.path.join(root, file), ' ---> ', e)

```
and the output:
```
...
Scanning:  D:/DumpStack.log
Scanning:  D:/DumpStack.log.tmp
Scanning:  D:/tét tiếng việt có được không.txt 
Yara Exception:  D:/tét tiếng việt có được không.txt  --->  could not open file "D:/tét tiếng việt có được không.txt"
Scanning:  D:/$RECYCLE.BIN\S-1-5-18\desktop.ini
...
```
I see unicode file names is supported from v4.2.0. So what am I doing wrong?

**Comment by CatyGreen** [comment]
Hi, any update on this? I'm facing the same problem with yara-4.2.3. Do I have to compile yara with some extra flags?

**Comment by hmn91** [comment]
> Hi, any update on this? I'm facing the same problem with yara-4.2.3. Do I have to compile yara with some extra flags?

I solved it by manually reading file and then passing data to scanner.

```
rules = yara.load('compiled_rules.bin')
for root, dirs, files in os.walk("D:/"):
    for file in files:
        try:
            print("Scanning: ", os.path.join(root, file))
            with open(os.path.join(root, file), 'rb') as f:
                rules.match(data=f.read(), callback=match_callback, which_callbacks=yara.CALLBACK_MATCHES)
        except yara.Error as e:
            print("Yara Exception: ", os.path.join(root, file), ' ---> ', e)
        except Exception as e:
            print("Exception: ", os.path.join(root, file), ' ---> ', e)
```

The downside I see is that it will have to load the entire file data into memory which can lead to memory related errors when scanning large files. But I believe that even if you scan in the usual way, yara scanner will do the same. So we should add some scan file size limit to make sure theres is enough memory.

**Comment by CatyGreen** [comment]
Thanks, the problem is that I'm using C version of yara (no python)... Not sure if I can do something similar....

**Comment by plusvic** [comment]
YARA 4.2.3 added support for unicode filenames on Windows to the command-line program. This means that you can invoke the `yara` executable with unicode paths. However, the `yr_scanner_scan_file` API in the YARA library, which is what `yara-python` uses under the hood when you call `rules.match(...)` with a file path, doesn't support unicode paths.

The workaround in Python is reading the file yourself and using `rules.match(data=...)` for scanning the data, as @hmn91 already found out.

If you are using the C library, don't  use `yr_scanner_scan_file`, instead read the data yourself into a buffer, and use `yr_scanner_scan_mem` for scanning the data. Alternatively, you can use [`yr_scanner_scan_fd`](https://yara.readthedocs.io/en/stable/capi.html#c.yr_rules_scan_fd), which receives a file handle instead of a path (this is what the command-line `yara` does). The file handle is created with the Windows API `CreateFile`, but you must compile your Windows program with unicode support, so that it get linked against `CreateFileW` which is the version that supports unicode paths.

**Comment by CatyGreen** [comment]
Sorry, I've repeated the tests and it doesn't work neither the compiled versions nor the source code. If there are some folders with unicode names, yara does not analyze the content inside them.

**Comment by CatyGreen** [comment]
Hi, I just want to give more details about my test.
If I compiled the code with Visual Studio it works fine with UNICODE, the problem is using MINGW.
I've tried adding "-municode -Wl,--subsystem,console" to Makefile.am
I've also add "-D_UNICODE -DUNICODE -D_CONSOLE" to CFLAGS.

The error that I get is the following:
```
libtool: link: gcc -Wall -municode -Wl,--subsystem -Wl,console -I./libyara/include -O3 -D_CONSOLE -D_UNICODE -DUNICODE -DUSE_WINDOWS_PROC -DDOTNET_MODULE -DHASH_MODULE -o .libs/yara.exe cli/args.o cli/common.o cli/threading.o cli/yara.o  -Llibyara/.libs /home/caty/yara-4.2.3/libyara/.libs/libyara.a -lmingw32 -lcrypto
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../lib/libmingw32.a(lib64_libmingw32_a-crt0_w.o): in function `wmain':
C:/M/mingw-w64-crt-git/src/mingw-w64/mingw-w64-crt/crt/crt0_w.c:23: undefined reference to `wWinMain'
```
I don't know why tries to resolve wWinMain, there is no WinMain in the source code...
