### ISSUE TITLE
Inconsistent detection rate

### ISSUE THREAD

**Issue by ajubakhanji** [VirusTotal/yara#1834]
**Issue:**

When scanning an open source repository of malware, one YARA rule-set consisting of approximately _11000_ rules had an _82%_ detection rate. Meanwhile, another rule-set consisting of approx. _36000_ rules had a _0.13%_ detection rate despite the fact that the previously mentioned rule-set producing the 82% detection rate is a **subset** of the second rule-set. 

Is this expected behavior when scanning with large rule-sets? 

**Expectation:**

The expectation is for the second & larger rule-set to have at least the same detection rate as the sub-set.

**Related information:**

 - OS: Debian 11.3
 - YARA version:  4.2.3

Thank you in advance for your support!

**Comment by plusvic** [comment]
That's definitely not the expected behaviour. Can you provide more details about the procedure that you are following? Are you using the command-line tool?

**Comment by ajubakhanji** [comment]
Hello again, 

Firstly, I want to begin by informing you that I encountered the same issue with YARA versions **4.1.3** and **4.0.5**. 

**More info about the procedure:**

-  Yes, the CLI is used with the following command: **yara -r -N <rule_set> <target_dir>**

-  The target scanned directory is an accumulation of the following open-source malware repos: 

https://github.com/fox-it/cobaltstrike-beacon-data.git

https://github.com/Endermanch/MalwareDatabase.git

https://github.com/vxunderground/MalwareSourceCode.git

https://github.com/jstrosch/malware-samples.git

https://github.com/fabrimagic72/malware-samples.git

- The whole rule-set, *main.yar* yielding a 0.13% detection rate, is:
[main.yar.zip](https://github.com/VirusTotal/yara/files/10252525/main.yar.zip)

- The subset, *subset.yar* yielding a 82% detection rate, is: 
[subset.yar.zip](https://github.com/VirusTotal/yara/files/10252526/subset.yar.zip)

Finally, to further test the hypothesis that this is occurring due to the rule-set size,  the main ruleset *main.yar* was split randomly into a size close to the subset and the detection rate was **60%**.

I hope this information as well as the provided rule-sets help you reproduce &/or verify this issue. 

Thank you!

**Comment by plusvic** [comment]
When you scan the files with `main.yar` are the results always the same? I mean, are the results changing for different runs of `yara` with the same rules and scanned files? If the results are consistent among different scans using `main.yar` it would be helpful if you can locate some file that should be detected by some rule and is not being detected.

**Comment by wxsBSD** [comment]
I took a look at main.yar and there are some global rules in there, which are likely causing some files not to match. This is one of the reasons I caution people against just taking rules off the internet and combining them into a giant set.

```
private global rule hatman_filesize : hatman
global rule isExecutable
global rule GlobalRuleExample
```

**Comment by plusvic** [comment]
@wxsBSD good catch!

**Comment by Pierre-Gronau-ndaal** [comment]
beside if the YARA ruleset is good or bad, maybe an investigation will make sense

**Comment by plusvic** [comment]
As @wxsBSD said, global rules completely distort your results. Consider a case when you have only two `.yar` files:


1.yar:
```
global rule global_false {
   condition: false
}
``` 

2.yar: 
```
rule always_true {
   condition: true
}
```

If you scan your files with `2.yar` alone, every file will match, but as soon as you combine `1.yar` and `2.yar` you won't get any matches at all, because the global rule is false of every file. You may be expecting that by combining both `.yar` files you should get at least the same number of matching files you got with `1.yar` alone, but that's not the case.

You have to options here, getting rid of all global rules before making your test, or using a different namespace for each file.

For example, this won't produce any matches:

```
yara -r 1.yar 2.yar <target_dir>
```

But this will match with every file:

```
yara  -r foo:1.yar bar:2.yar <target_dir>
```

That's because in the second case you are forcing each `.yar` file to have a different namespace, and the global rule in `1.yar` won't affect the rule in `2.yar`.

**Comment by anotherbridge** [comment]
We can confirm, when removing the global rules from the above posted ruleset `main.yar` by @ajubakhanji that the detection rate is much higher than expected. 

To conclude this, three tests were performed in total:
1.  The `main.yar` was used and all global rules were removed. This yielded to a detection rate of of 82.50%. 
2. The global rules were still used, but split up into a different file, then both approaches presented by @plusvic were investigated: 
   1. Using both rule files in the same namespace, yielded a detection rate of about 1%, which interestingly was higher then if both files were combined. 
   2. Having both rule files in different namespaces, yielded a detection rate of 82.50% percent, where the absolute amount of detections was slightly higher than in the first case. This does make sense, since there are three more rules included. 

After having performed these tests, it can be said that it seems that as @wxsBSD suggested, the global rules really seemed to mess up the detection. 

Since to me, it wasn't obvious from the documentation that this could be such an issue, I would suggest to include an explicit warning/hint in there pointing that using global rules in a wrong context could mess up the expectation of what rules are detecting.

**Comment by GWHAYWOOD** [comment]
Shouldn't this issue be closed?
