### ISSUE TITLE
yara imphash and pefile imphash are different

### ISSUE THREAD

**Issue by syyoo84** [VirusTotal/yara#1943]
**Describe the bug**
yara imphash and pefile imphash are different
So you can't use imphash in yara rule.
Any reason?
sha256: 803d740df04cc995fd7010473be6b06e190c7ca5114a525d951ae11e7394ab12
yara imphash: ecb1f45f310c2bf07612a019ce157b0f
pefile imphash: b22fdcce4de8993adbff1ff244d1b4a5
https://www.virustotal.com/gui/file/803d740df04cc995fd7010473be6b06e190c7ca5114a525d951ae11e7394ab12/details

**To Reproduce**

**Expected behavior**

**Screenshots**

**Please complete the following information:**
 - OS: Windows
 - YARA version: 3.8.0

**Additional context**

**Comment by wxsBSD** [comment]
Great find! I'm pretty sure this has been broken since I first implemented imphash in YARA back in 2014. I based it off the Mandiant blog post, which I'm pretty sure did not say anything about this case. Turns out the pefile code has been ignoring names that are empty strings, or otherwise evaluate to false in python, for at least the last 10 years (according to blame): https://github.com/erocarrera/pefile/blob/593d094e35198dad92aaf040bef17eb800c8a373/pefile.py#L5871-L5872

I've put up a fix for this along with a test case so we shouldn't regress on it in the future either.

**Comment by syyoo84** [comment]
> Great find! I'm pretty sure this has been broken since I first implemented imphash in YARA back in 2014. I based it off the Mandiant blog post, which I'm pretty sure did not say anything about this case. Turns out the pefile code has been ignoring names that are empty strings, or otherwise evaluate to false in python, for at least the last 10 years (according to blame): https://github.com/erocarrera/pefile/blob/593d094e35198dad92aaf040bef17eb800c8a373/pefile.py#L5871-L5872
> 
> I've put up a fix for this along with a test case so we shouldn't regress on it in the future either.

Here's another case.
If the IAT function name contains null bytes as well as a ' mark, it is ignored and an imphash hash is judged to be created.
So yara imphash and pefile imphash are different.

https://www.virustotal.com/gui/file/10fdf28e81f443299fb2753fa06065d2913d8275a322f27556728e6db32510e7/details

**Comment by wxsBSD** [comment]
Ok, I'll take a look in a bit. Thanks for bringing it up!

**Comment by syyoo84** [comment]
Thank you for your support.
Thank you for being able to contribute to the Yara community by reporting bugs at NSHC ThreatRecon Team.
