### ISSUE TITLE
Question: How does Yara handle conditions of multiple rules under the hood?

### ISSUE THREAD

**Issue by dmknght** [VirusTotal/yara#2127]
I would like to understand more how Yara handles conditions of multiple rules under the hood so I can improve my ruleset. For example, I have sample rules:
- style 1:
```
rule elf_malware_1 {
  strings:
    $ = "sample 1"
  condition:
   uint32(0) == 0x464c457f and all of them

rule elf_malware_2 {
  strings:
    $ = "sample 2"
  condition:
   uint32(0) == 0x464c457f and all of them
```

- Style 2:
```
private rule elf_magic {
  condition:
    uint32(0) == 0x464c457f
}

rule elf_malware_1 {
  strings:
    $ = "sample 1"
  condition:
   elf_magic and all of them

rule elf_malware_2 {
  strings:
    $ = "sample 2"
  condition:
   elf_magic and all of them
 }
```

Yara could run comparison in 2 ways:
1. Check `uint32(0) == 0x464c457f` then `sample 1` then `uint32(0) == 0x464c457f` (again) then `sample 2`
2. Check `uint32(0) == 0x464c457f` then either `sample 1` and `sample 2`

My questions:
1. Which way Yara does (comparison I said above)
2. Is there any differences between 2 styles of writing rules (beside 2nd style should decrease some memory usage in theory)?

**Comment by plusvic** [comment]
YARA will first scan the file looking for both "sample 1" and "sample 2". Then it will evaluate `elf_magic` and store the result for later use.  While evaluating the other two rules, it will use the previously stored result.

In this case, because the condition of `elf_magic` is very simple, you won't notice any difference between both approaches. If the condition of `elf_magic` would be something more complicated, like a rule with a very large loop, the second approach would be better, because the loop is executed once.
