### ISSUE TITLE
Imphash not hitting

### ISSUE THREAD

**Issue by jcannell** [VirusTotal/yara#337]
Hi,

I was trying to write a rule that used an imphash today. I have the right imphash according to VT and pefile. Here is my rule

import "pe"

rule cryptowall_1 : ransomware
{
   meta:
      author      = "Joshua Cannell"
      description = "Cyptowall Ransomware 3.0, Visual C++"

   condition:
      pe.imphash() == "251177b9dbdc928d5ac0e23bfe73ad1d"

}

When i run the rule against my file (sha256: 403a80f653631d2e07c181c0e76d575ed3b875305b5bf3ccc617d70e54a79d1f) I don't get anything. The file is on VT.

Never tried imphash w/yara before today, seems like I'm doing it right, though. Am I missing something?

**Comment by wxsBSD** [comment]
I can take a look at this early next week.

**Comment by wxsBSD** [comment]
This was likely broken in https://github.com/plusvic/yara/commit/1cc98f75fa922614aa440ccf9c397d65db7c825c. The file in question imports more than 256 functions from RPCRT4.dll. I checked the PE specification and don't see anywhere that mentions this limit, so it seems both arbitrary and incorrect to have in YARA. I understand the need for it but it does break things in this case (and also anyone using the ```imports()``` function will potentially see incorrect results.

Adding @shanehuntley since he is the one who made the commit in question.

**Comment by plusvic** [comment]
The best idea is probably increasing MAX_PE_IMPORTS to some value unlikely seen in actual PE files. Maybe 16384?

**Comment by wxsBSD** [comment]
That's reasonable but still arbitrary. When parsing imports there isn't that much data used per import, so what's wrong with having no limit?

One other option is to move the import parsing to be an "on demand" thing that is done only during a function that requires it (imphash and imports). The trade off would be a longer run time but a lower memory footprint as neither function would allocate anything while parsing the import table. Just an idea...

Ultimately I can see bumping the limit as you suggest but it still seems arbitrary to me. I'd love to find an example that causes "blow up".

**Comment by plusvic** [comment]
Maybe @shanehuntley can provide some problematic PE. I suspect he introduced this limit because of some malformed PEs causing thousands or even millions of iterations on that loop.

**Comment by jcannell** [comment]
I like the "on demand" idea. No reason to parse the imports unless it's needed, yes?

And I think it's a good idea to have a limit, even if it seems arbitrary. I'm not real familiar with yara at the source level but I know things tend to get abused when there aren't limits :\

**Comment by jcannell** [comment]
found another one today, still cryptowall:

https://www.virustotal.com/en/file/8a07721864d8bcb92f3c4e78ae5b6e87e60d92930c60a44b019bf09622caca47/analysis/1439301773/

**Comment by jcannell** [comment]
And here is a Bunitu Proxy Trojan that doesn't hit on imphash, just uploaded this today.

https://www.virustotal.com/en/file/8aad575ee69620c6f63aa64e394ad30c223c35a4e30d3632605b29eb6b168488/analysis/1439303313/

Took a closer look at imports. I didn't see any more than 256 functions imported from a single dll. What could be the issues for this imphash not hitting, I wonder?

pe bear: http://imgur.com/HQxq5LM

**Comment by wxsBSD** [comment]
The second file you reference (https://www.virustotal.com/en/file/8aad575ee69620c6f63aa64e394ad30c223c35a4e30d3632605b29eb6b168488/analysis/1439303313/) doesn't hit on imphash because the imports for GDI32.DLL fail to parse. This is because using ```OriginalFirstThunk``` for ```pe_rva_to_offset()``` is returning an offset that is incorrect. This is likely because the import table itself is corrupt and YARA is taking a fairly strict stance on parsing that other tools do not.

I know using 010 editor and their PE template complains about the corruption. I am having problems trying another parser (pe-parse from Trail Of Bits) to see how it behaves, but I suspect this is likely a case of a corrupt import table which I'm not sure there is much we can (or should) do.

**Comment by jcannell** [comment]
Is this "strict stance" really necessary? The reason I ask is, if I can get an impash using pefile and/or VT, then to me this only seems like a shortcoming and not a "feature" of yara.

I would love to see the imphash of these files (and many others that I've recently discovered) hitting with yara if at all possible. It will make it a more viable tool overall.

**Comment by wxsBSD** [comment]
I agree that there may be some wiggle room to be less strict here. Clearly other tools behave differently. Sadly I am tied up with other things for a bit and am unable to dig deeper into what is going on, but will try and keep an eye on this issue if it hasn't moved forward by the time I am able to look into this.

**Comment by jcannell** [comment]
I understand. I hope you guys might be able to improve this whenever time allows.

**Comment by wxsBSD** [comment]
I just put up a PR to bump the limit to 16384, as discussed here.

I also took a deeper look into the secondary issue (8aad575ee69620c6f63aa64e394ad30c223c35a4e30d3632605b29eb6b168488 and not recognizing imports from GDI32.DLL). As I mention above, the call at https://github.com/plusvic/yara/blob/master/libyara/modules/pe.c#L830 is returning 0x9090 which when parsed as an ```IMAGE_THUNK_DATA32``` structure has values which are just plain wrong. The right thing to do for this file is to use ```import_descriptor->FirstThunk``` to get the imports. Does it make sense to re-work this function to try using ```OriginalFirstThunk``` first and if that fails attempt again with ```FirstThunk```. As things stand right now, we only use ```FirstThunk``` if ```OriginalFirstThunk``` offset is less than 0, which is not true in this case. I suspect it may be better to attempt parsing and if it fails to attempt again using ```FirstThunk```?
