### ISSUE TITLE
Increase default RE_MAX_SPLIT_ID

### ISSUE THREAD

**Issue by jovimon** [VirusTotal/yara#548]
Hello,
We at YaraRules had a rule with an [extra long regex](https://github.com/Yara-Rules/rules/blob/cf753b748a84e9b79f83558f2ee3204261567a6d/malware/MALW_AdGholas.yar#L77) that had to remove because caused errors on default Yara 3.5.0 packages. It worked fine on earlier releases (tested on 3.4.0).

Today, reviewing issue #492 I found that increasing RE_MAX_SPLIT_ID constant defined in libyara/re.c to 255, its max allowed size at the moment, and recompiling yara 3.5.0 removed the error and made the analysis work. 
Just a few questions:
- Why did you choose this value for this constant?
- Can you increase it? Can you make it a 16 bit integer so it can be increased even further if someone needs it?
- What are the drawbacks of increasing this number?
- Can you make the error more "user-friendly" explaining why it happened?

Thank you very much!

**Comment by plusvic** [comment]
*Why did you choose this value for this constant?

The value was chosen arbitrarily, it was supposed to cover the most typical regular expressions, but turned out that people sometimes write pretty complex regular expressions for YARA.

*Can you increase it? Can you make it a 16 bit integer so it can be increased even further if someone needs it?

Yes, it can be increased. And I'm working on other fixes to this issue in https://github.com/VirusTotal/yara/commits/more_compact_re_code

*What are the drawbacks of increasing this number?

The drawback is a little increase in memory consumption, but that's all.

*Can you make the error more "user-friendly" explaining why it happened?

Sure, but once the new patches are deployed this shouldn't happen that frequently. Idealistically this limit shouldn't be hit for normal use of regular expressions.

**Comment by jovimon** [comment]
Thank you very much for your comments.

I'm not a great C coder but made a small PR to make the error more "user-friendly".

Hope it's not very bad and you like it.

**Comment by plusvic** [comment]
Version 3.5.0 was prone to reaching the RE_MAX_SPLIT_ID limit, but after fixing some issues causing this problem it shouldn't be an issue anymore.
