### ISSUE TITLE
Rule tags - allow hyphens?

### ISSUE THREAD

**Issue by dspruell** [VirusTotal/yara#555]
YARA 3.5.0

Noted in YARA that rules specifying tags containing a hyphen are invalid. I understand this is due to them following the same restrictions as rule identifiers which follow C conventions for identifier naming.

Sample rule headers and errors:

```
rule foo : bar baz-qux

/rules/main.yar(1816): error: syntax error, unexpected '-', expecting '{'
```

Noticed too a hyphenated tag name causes the invalid tag name to match an existing tag if the part before the hyphen matches a valid tag.

```
rule foo : bar bar-qux

/rules/main.yar(1816): error: duplicated tag identifier "bar"
```

We use a metadata taxonomy where hyphenated labels are commonplace and I was wondering if this is a necessary restriction in YARA, or can this behavior be changed to allow hyphens in the rule tags?

Possibly same request for the rule identifier - just curious if it's feasible to loosen restrictions on identifiers and allow hyphens in the rule identifier?

**Comment by plusvic** [comment]
The reason for not allowing hyphens in identifiers and tags is because it is used as the minus operator. They could be accepted for tags, as tags can't appear in conditions, but for rule identifiers it introduces problems for the parser, you can't tell if foo-bar is a single identifier or if it means foo minus bar. That's why must programming language don't accept hyphens in identifiers.

In order to keep things simple and coherent I prefer not allowing hyphens in tags and handle them as standard identifiers. There are also some ideas about allowing tags to be used in conditions, and allowing hyphens in tags could be a problem in the future for implementing such features.

**Comment by dspruell** [comment]
Understood, thanks for the explanation.
