### ISSUE TITLE
Error in scanning yara rule

### ISSUE THREAD

**Issue by viper2020** [VirusTotal/yara#557]
Hi guys,

I wrote an yara rule and tried to run as root.I ran the rule through the terminal.
In my understanding,yara rules will be scanned through the entire system,but I am getting errors like; 

error scanning //proc/bus/pci/00/02.0: internal error: 4
error scanning //proc/sys/vm/compact_memory: could not open file

Could somebody help me with this issue?

**Comment by hillu** [comment]
Hi @viper2020,

> error scanning //proc/bus/pci/00/02.0: internal error: 4
> error scanning //proc/sys/vm/compact_memory: could not open file
>
> Could somebody help me with this issue?

On Unix systems, you generally don't want to scan "special" files such
as device nodes or files within the /proc or /sys filesystems, even as
root.

The "internal error 4" stands for ERROR_COULD_NOT_MAP_FILE which likely
happens due to SIGBUS being delivered to the yara process.

Cheers,
-Hilko

**Comment by viper2020** [comment]
Thanks for the response,

What if I need to scan the special files too?
Is there any way to do that?
I just need to check for any false positives.

**Comment by hillu** [comment]
* viper2020:

> Thanks for the response,
>
> What if I need to scan the special files too?

Not possible with yara (the command line tool), you'll have to code your
own logic around libyara.

Beware, reading from some files in /proc, /sys, or /dev may make your
system unstable.

Cheers,
-Hilko

**Comment by viper2020** [comment]
Thanks
