### ISSUE TITLE
Search "at pe.entry_point" produces multiple matches.

### ISSUE THREAD

**Issue by diwoky** [VirusTotal/yara#596]
Search for the hex string using `$ep_data at pe.entry_point` produces multiple matches on various offsets (see attached rule_#1.match)
EP offset seems to be properly found : entry_point = 2014 (0x7DE)

[report.zip](https://github.com/VirusTotal/yara/files/716991/report.zip)
```
import "pe"

rule Test1
{
  strings:
    $ep_data = { E9 }
  condition:
    $ep_data at pe.entry_point       
}
```
vs
```
import "pe"

rule Test2

{
  strings:
    $ep_data = { E9 }
  condition:
    $ep_data at 0x7DE
}
```

**Comment by wxsBSD** [comment]
This is intentional. What is happening in Test2 is that 0x7de is recognized as a primary expression which results in $ep_data only being searched for at that specific offset. This is an optimization. As soon as you include another rule in that file which has a string of `{ E9 }` without this optimization then you will see it print matches everywhere again in Test2.

In the Test1 case `pe.entry_point` is an identifier (not a primary expression) and while it is recognized as identifying an integer the same optimization is not applied because the value identified by pe.entry_point is not known at rule compilation time.

It is possible to get Test2 behavior in Test1 by using the deprecated `entrypoint` keyword instead of `pe.entry_point` but I would not recommend that.

It may be possible to get this optimization behavior in Test1, but I'm not sure the level of effort required here and if it is even worth the additional complexity.

**Comment by diwoky** [comment]
Thank you for explanation, I think issue can be closed.
