### ISSUE TITLE
Implement NodeJS API bindings

### ISSUE THREAD

**Issue by trufae** [VirusTotal/yara#598]

**Comment by stephenwvickers** [comment]
Hi @trufae

I will be looking to do this as an independent npmjs module myself fairly soon.

If you have any specific requirements i would.love to hear them.

Steve

**Comment by stephenwvickers** [comment]
Hi @trufae 

Node.js bindings for YARA are now available at:

https://www.npmjs.com/package/yara

@plusvic You can probably close this ticket now.

Steve

**Comment by plusvic** [comment]
@stephenwvickers Great!

**Comment by trufae** [comment]
npm install yara fails in mac.

**Comment by stephenwvickers** [comment]
Hi @trufae 

Since this is now a node-yara module issue can I please ask you open an issue under that GitLab repo:

https://github.com/stephenwvickers/node-yara

For context I will answer here initially.

This first version supports Linux platforms only, I have pointed this out in the docs.

If you do absolutely need Mac OS support, and you are willing to work with me to test a release once it is implemented, then please open an issue under the node-yara repo given above.

Thanks

Steve

**Comment by trufae** [comment]
thanks! i have send a PR fixing a bunch of syntax issues and porting it to
OSX
