### ISSUE TITLE
Avoid nested hits

### ISSUE THREAD

**Issue by trufae** [VirusTotal/yara#624]
if you look for `/foo(.*)/` it will match twice in "foofoobar", this is not the expected behaviour. i think Yara should continue searching right after the end of the match. Or at least have an option to toggle this behaviour

**Comment by trufae** [comment]
```
$ ls
rules.yar test.txt

$ cat test.txt
foofoobar

$ cat rules.yar
rule regex : bug {
	meta:
		author = "pancake"
	strings:
		$regex = /foo([^\ ]*)/
	condition:
		all of them
}

$ yara -s rules.yar test.txt
regex test.txt
0x0:$regex: foofoobar\x0A
0x3:$regex: foobar\x0A
```

**Comment by plusvic** [comment]
That's the intended behavior indeed. YARA reports all the offsets within the file where the string or regexp matches, no matter if the matches overlap. Why? Because in YARA you can create conditions like `$regexp at 3` which basically means: Does $regexp match at offset 3? In this case the answer is true, the regexp matches at offsets 0 and 3 for the string "foofoobar".

Adding a command-line option for showing only non-overlapping matches is relatively easy, but it introduces further issues, for example suppose that your condition is `$regexp at 3`, and you run:

```
$ yara --print-non-overlapping-matches-only -s rules.yar test.txt
regex test.txt
0x0:$regex: foofoobar\x0A
```

YARA will correctly report that the rule is matching, but it will only show the match at offset 0. Users could start wondering why `$regexp at 3` is true but they only see the match at offset 0. As the user is explicitly using `--print-non-overlapping-matches-only` he probably understands what's going on, but unless this option has a really important practical use-case I would prefer not adding it. 

Can you provide more context on why do you miss this feature?

**Comment by trufae** [comment]
yes, that would be fine for me, in r2 this is done with `e search.overlap=false`. i understand that this shouldnt be an option enabled by default. but it makes sense for my use cases where i just want to quickly identify files instead of carving the whole set of matches for all the rules.

**Comment by melomac** [comment]
Out of curiosity, can we assume YARA to always return regex nested hits _after_ the longest matched string?

**Comment by plusvic** [comment]
@melomac what do you mean exactly? I'm not understanding your question.

**Comment by melomac** [comment]
In #504 we see the longest match is also the first one, and local tests confirmed that assumption.

If I am to filter smaller matches according to the string upper bound — i.e. offset + len(data) — I could either:

1. assuming longest match is always first, simply discard other strings where upper bound is known
2. or compare the offset for each strings where upper bound is known and keep the one with the lowest offset i.e. the longest data

Of course, since solution 2 doesn't rely on an assumption, it natually seems to be the right way, but this also got me wondering, hence the question: is the longest match string always the first match string?

**Comment by plusvic** [comment]
That assumption is ok for matches at consecutive offsets, but keep in mind that the same pattern can match multiple times in different regions of the file, for example, suppose you have a pattern `$a = /[a-z]+/` and a file `abcdefg0abcdefg`, the matches would be:
```
0x0:$a: abcdefg
0x1:$a: bcdefg
0x2:$a: cdefg
0x3:$a: defg
0x4:$a: efg
0x5:$a: fg
0x6:$a: g
0x8:$a: abcdefg
0x9:$a: bcdefg
0xa:$a: cdefg
0xb:$a: defg
0xc:$a: efg
0xd:$a: fg
0xe:$a: g
```

The `0` in the scanned data breaks the sequence of matches in two.

**Comment by melomac** [comment]
Thank you for confirming the assumption. I totally agree a pattern could match different regions and, in this case, the upper bound — offset + len(data) — will reflect the new region.
