### ISSUE TITLE
Implement yara -u to `uniq` the results

### ISSUE THREAD

**Issue by trufae** [VirusTotal/yara#625]
Sometimes the same rule matches several times in a single binary, it will be good to have yara -u to | uniq the results and only the first match of any rule

**Comment by wxsBSD** [comment]
Can you give an example of the same rule matching multiple times. I haven't read the code in a while but I think this shouldn't happen.

**Comment by trufae** [comment]
```
pancake@~/yara-bug$ ls
rules.yar test.txt
pancake@~/yara-bug$ cat test.txt
foofoobar
pancake@~/yara-bug$ cat rules.yar
rule regex : bug {
	meta:
		author = "pancake"
	strings:
		$regex = /foo([^\ ]*)/
	condition:
		all of them
}

pancake@~/yara-bug$ yara -s rules.yar test.txt
regex test.txt
0x0:$regex: foofoobar\x0A
0x3:$regex: foobar\x0A
pancake@~/yara-bug$
```

**Comment by wxsBSD** [comment]
This is not the rule matching twice, but the strings. My opinion is this is not a good idea, because I want to know all the offsets when I ask to see the strings.

**Comment by trufae** [comment]
yes, i have posted the example of the wrong issue (moved there). check the comment above again, i its now updated.

the behaviour im looking for is to stop searching for a rule that matches exactly the same string. This will speedup results and reduce noise in output, because for me in this case i just want to see that this file contains "foo" at 0, and i dont care if there's any other foo after that

**Comment by plusvic** [comment]
The option you are looking for is probably `--fast-scan`. With this option once YARA finds a match for a particular string it stops looking for more matches for the same string. Notice however that $str1 and $str2 are considered different strings even if they are both "foo", so YARA will look for the first match for $str1 and the first match for $str2. Also, not all string are suitable to be optimized with `--fast-scan`, if the string is used in a condition like `#str > 10` (number of occurrences of $str larger than 10) YARA will keep looking for more matches even if you are using `--fast-scan`, because it needs them in order to verify if the condition is true or not.
