### ISSUE TITLE
new yara versions fail to parse some big rules

### ISSUE THREAD

**Issue by mbandzi** [VirusTotal/yara#692]
Hello,

sometimes I have very big rules (KBs) but newer yara versions cannot parse them for some reason. Release 3.6.0 is ok, but both release 3.6.2 and actual master fail with strange message that is often non deterministic:
`mingw-test.yara(7): error: invalid hex string "$1": *non-deterministic non-printable gibberish*`
 
Example rule file:
[mingw-test.yara.zip](https://github.com/VirusTotal/yara/files/1112202/mingw-test.yara.zip)

**Comment by mbandzi** [comment]
After looking into closed issues, this is probably duplicate of #688, so I can cut strings in my rules.
I do not know what exactly limit mentioned in #688 does, but if long hex strings are discouraged, maybe
`#define MAX_HEX_STRING_TOKENS           10000`  should be adjusted aswell. Also printed error message should be better.

**Comment by plusvic** [comment]
In ac368637fa2bdd32614b134ba5236d2717ed1a56 I'm removing `MAX_HEX_STRINGS_TOKENS` as it is not necessary anymore. A better error message is printed when `RE_MAX_AST_TOKENS` is reached. I'm not increasing `RE_MAX_AST_TOKENS` because with a value of 7500 the program overflows the stack when compiled with AddressSanitizer. Let's keep it at 6000, which is enough for reasonably long strings.
