### ISSUE TITLE
Feature Request, Get current time

### ISSUE THREAD

**Issue by securitykitten** [VirusTotal/yara#743]
When writing rules looking for modified timestamps within binaries, it'd be useful to gain access to the current scan (or system time) for checking.  

I could imagine scenarios where the following rule would be useful.
```
import "time"
import "pe"
rule timestamp_in_future
{
conditions:
pe.timestamp > time.now + 86400
}
```

**Comment by wxsBSD** [comment]
I thought about this when I was doing the signatures stuff years ago. I decided against implementing this because it would make rules that use it temporally dependent. I didn’t like the idea of a rule firing one second and not the next, for the same file.

I certainly see value in the idea though. I just couldn’t convince myself it was worth the trade off.

**Comment by plusvic** [comment]
Yes, it could be confusing if you haven't seen the rule, but as a soon as
you see that the current time is involved in the condition you will
probably figure out what's happening. I see a lot of value to this in
VirusTotal's malware hunting for example, where you could set a rule that
triggers only on recently compiled PE files or stuff like that. Without
having to worry about your rule becoming obsolete in the future.

**Comment by wxsBSD** [comment]
So I’m thinking of three different ways to implement this.

1. Make a reserved word in the language that is converted to the current time in seconds at compile time. This means if the rules are saved and reloaded at a later time the value in the rule won’t change.

2. Have time be a keyword that is converted to the current time at runtime. I’m thinking this would be a new operation in exec.c.

3. Have time be a module with a now() function so it is resolved at runtime. Using a module for this could give us more flexibility in the language, by being able to do things like time.future(3600) which would be logically equivalent to time.now() + 3600.

I’m inclined to go with either option 2 for simplicity or option 3 for flexibility.

What’s your opinion?

**Comment by plusvic** [comment]
Definitely option 3, much more flexible and doesn't require changes in the language itself.

**Comment by wxsBSD** [comment]
I have `time.now()` implemented in a module. It returns the number of seconds since the epoch, using time(3). I don't have a Windows machine to port it over to there, but maybe after I publish the PR I can get around to it.

Other than `time.now()` can you think of any other functions involving time that would be useful to have @securitykitten? I'm happy to add them!

**Comment by securitykitten** [comment]
Wow, thanks for the quick turn around on the module.  I'd imagine that having simple numerical operations available (which they already are) should be enough for most use cases.
