### ISSUE TITLE
Trying to use yara with multiple rules from directory

### ISSUE THREAD

**Issue by alvosec** [VirusTotal/yara#753]
I'm trying to run yara with multiple rules from directory, but it will return me error:

`yara rules/ /dir/to_scan`

`error: input in flex scanner failed`

Currently I'm running yara 3.4.0.

What can cause that error, is it a bug or something else?

**Comment by plusvic** [comment]
YARA doesn't accept a directory with multiple files as an input for rules. In version 3.4.0 a single rules file can be used. With the latest version in master you can specify multiple files, like in:

```
$yara rules_1 rules_2 rules_3 file_to_scan
```

**Comment by rfandia** [comment]
same issue with me 

```
yara billgates_rule /etc/*
/etc/adjtime(1): error: syntax error, unexpected floating point number
```

**Comment by erikdemarco** [comment]
"YARA doesn't accept a directory with multiple files as an input for rules."

This feature is requested multiple times. People who are new to this repo will think this very basic feature exist. They will know its not possible after trying.

With just this 1 feature I'm very sure yara will be very powerful. Because we can just combine it the way we want it fast.

**Comment by addoyle** [comment]
Apologies for replying to an old thread, but you could also do something like this:

```bash
yara $(find . -name "*.yar") file_to_scan
```

**Comment by tpicpal** [comment]
this command was working for me: 
`$rules = Get-ChildItem -Path "C:\YARA\YARA-Windows-Server\rules" -Recurse -Include *.yara, *.yar`
`foreach ($rule in $rules) { & "C:\YARA\yara.exe" $rule D:\ >> "C:\YARA\yara_results.txt" 2>> "C:\YARA\yara_errors.log" }`
