### ISSUE TITLE
Issues with warnings when attempting to scan files.

### ISSUE THREAD

**Issue by highanglecav** [VirusTotal/yara#812]
This is a sample of the errors I get when scanning, but I see this from almost every rule I've tried to use.

yara -m Malicious_Documents_index.yar /home/remnux/Desktop/share/Test\ Malicious\ DDE\ File/filename-42.doc
./Malicious_Documents/Maldoc_MIME_ActiveMime_b64.yar(20): warning: $activemime is slowing down scanning
./Malicious_Documents/maldoc_somerules.yar(53): warning: $a is slowing down scanning
./Malicious_Documents/maldoc_somerules.yar(63): warning: $a is slowing down scanning (critical!)
./Malicious_Documents/maldoc_somerules.yar(73): warning: $a is slowing down scanning (critical!)
./Malicious_Documents/maldoc_somerules.yar(114): warning: $a is slowing down scanning
./Malicious_Documents/Maldoc_PDF.yar(66): warning: $attrib contains .*, consider using .{N} with a reasonable value for N
./Malicious_Documents/Maldoc_PDF.yar(159): warning: $shell is slowing down scanning
./Malicious_Documents/Maldoc_PDF.yar(261): warning: $reg is slowing down scanning
./Malicious_Documents/Maldoc_PDF.yar(296): warning: $reg0 contains .*, consider using .{N} with a reasonable value for N
./Malicious_Documents/Maldoc_PDF.yar(298): warning: $reg1 contains .*, consider using .{N} with a reasonable value for N
./Malicious_Documents/Maldoc_PDF.yar(403): warning: $reg0 contains .*, consider using .{N} with a reasonable value for N
./Malicious_Documents/Maldoc_PDF.yar(404): warning: $reg1 contains .*, consider using .{N} with a reasonable value for N

**Comment by wxsBSD** [comment]
The warnings are because the rules you're using are going to slow down scanning. There isn't anything wrong with YARA in this case. It looks like you're using the https://github.com/yara-rules/rules repo. I suggest getting them to update their signatures if possible.

**Comment by highanglecav** [comment]
This is really the first time I've used Yara is there a better repo to get that might correct these issues?

**Comment by wxsBSD** [comment]
Yes, these are warnings because some of the rules are going to cause the YARA scanning process to perform poorly. The problem is not with YARA but with the rules. It looks like you're using rules from the https://github.com/yara-rules/rules repo, and this should be an issue there. I don't really know what they are going to do, I just know you're not likely to find good support for them here as it isn't really a bug to be addressed.

Also, if you're just experimenting with YARA these are likely harmless warnings. You're not going to be running those rules on a large volume of files so the sub-optimal performance those rules cause is not a big deal.

**Comment by highanglecav** [comment]
Thank you. Didn't need an account until now.
