### ISSUE TITLE
error: duplicated identifier

### ISSUE THREAD

**Issue by s0i37** [VirusTotal/yara#858]
Hello.
I have a lot of databases from various vendors. And when I use all in one moment I have this error.
How can I ignore this error? I update this databases sometimes and I can't remove all duplicates every time.

**Comment by plusvic** [comment]
That's probably because you have rules with the same name. In the best case scenario the duplicated identifiers belong to rules that are exactly the same (two or more vendors can be using rules from a common source).

You can not ignore the error, but you can use a different namespace for each vendor. This can't be done with the command-line tool, but you could use [yara-python](https://github.com/VirusTotal/yara-python) to compile the rules and scan your files. [Here](http://yara.readthedocs.io/en/v3.7.0/yarapython.html#using-yara-from-python) you can find how to use namespaces with `yara-python`.
