### ISSUE TITLE
YARA C API scanning running processes OS X

### ISSUE THREAD

**Issue by jemik** [VirusTotal/yara#875]
Hi. This is more of a question, then an issue. 
Im trying to run yr_scanner_scan_proc on all running processes, but after the first PID, my app exits with:  cant not attach to process (try running as root).
Do I need to spawn a new thread, for every pid? IE. Create a new scanner for each proc?

Thanks in advance.

**Comment by plusvic** [comment]
No, you don't need to create a separate thread for scanning each process, you can scan one process at a time with the same scanner on a single thread.

Does this happens always with the second process independently of which process it is? Or the second process is always the same one?

As the error suggests the problem is that couldn't attach to the process for some reason, maybe because it's a system protected process or some reason.

**Comment by jemik** [comment]
Thanks for the second set of eyes:)
Made me realize that I exit the program, when an error occurs. 
Total brain fart on my behalf. 

Thanks
