### ISSUE TITLE
yr_stopwatch_elapsed_us divide by 0

### ISSUE THREAD

**Issue by Tigzy** [VirusTotal/yara#987]
Hey, another issue from a crash dump. 
sw->frequency.QuadPart happens to be 0 (for some reason). We need guard here.

![image](https://user-images.githubusercontent.com/9531438/48783421-a6332800-ece0-11e8-9a04-159a0b303672.png)

**Comment by rspeaker** [comment]
We just ran into this.  In our case the problem occurred  when the call to yr_arena_create failed in yr_scanner_scan_mem_blocks.  When yr_arena_create fails, there is a goto _exit:

 result = yr_arena_create(1048576, 0, &scanner->matches_arena);

  if (result != ERROR_SUCCESS)
    goto _exit;

yr_stopwatch_elapsed_us is called within the _exit block even though the stopwatch wasn't yet initialized which leads to the divide by zero since frequency was not set.   There may be other cases like this as well

**Comment by plusvic** [comment]
@rspeaker, the issue you mentioned was fixed in https://github.com/VirusTotal/yara/commit/be3b77b633e2d1ab6fb3292044519e0b36ebaab1
